// <auto-generated />
namespace MVCPrueba.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creando_spNotas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creando_spNotas));
        
        string IMigrationMetadata.Id
        {
            get { return "201803212218348_creando_spNotas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
